import { Achievement } from '../types/game';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_thousand',
    name: 'First Thousand',
    description: 'Earn your first $1,000',
    emoji: '💵',
    condition: { type: 'money', amount: 1_000 },
    reward: { gems: 10 },
    unlocked: false,
    progress: 0,
    target: 1_000,
  },
  {
    id: 'first_business',
    name: 'Entrepreneur',
    description: 'Buy your first business',
    emoji: '🤝',
    condition: { type: 'business_count', count: 1 },
    reward: { gems: 15, tapMultiplier: 1.05 },
    unlocked: false,
    progress: 0,
    target: 1,
  },
  {
    id: 'first_million',
    name: 'Millionaire',
    description: 'Reach $1,000,000 net worth',
    emoji: '💰',
    condition: { type: 'net_worth', amount: 1_000_000 },
    reward: { gems: 50, incomeMultiplier: 1.1 },
    unlocked: false,
    progress: 0,
    target: 1_000_000,
  },
  {
    id: 'first_billion',
    name: 'Billionaire',
    description: 'Reach $1,000,000,000 net worth',
    emoji: '🤑',
    condition: { type: 'net_worth', amount: 1_000_000_000 },
    reward: { gems: 200, incomeMultiplier: 1.25 },
    unlocked: false,
    progress: 0,
    target: 1_000_000_000,
  },
  {
    id: 'first_mansion',
    name: 'Real Estate King',
    description: 'Buy the Mega Mansion',
    emoji: '🏰',
    condition: { type: 'luxury_owned', id: 'mega_mansion' },
    reward: { gems: 100, incomeMultiplier: 1.15 },
    unlocked: false,
    progress: 0,
    target: 1,
  },
  {
    id: 'passive_million',
    name: 'Passive God',
    description: 'Earn $1,000,000 per second passively',
    emoji: '⚡',
    condition: { type: 'passive_income', amount: 1_000_000 },
    reward: { gems: 150, incomeMultiplier: 1.2 },
    unlocked: false,
    progress: 0,
    target: 1_000_000,
  },
  {
    id: 'ten_businesses',
    name: 'Business Empire',
    description: 'Own 10 businesses',
    emoji: '🏙️',
    condition: { type: 'business_count', count: 10 },
    reward: { gems: 75, incomeMultiplier: 1.12 },
    unlocked: false,
    progress: 0,
    target: 10,
  },
  {
    id: 'tap_maniac',
    name: 'Tap Maniac',
    description: 'Tap 10,000 times',
    emoji: '👆',
    condition: { type: 'tap_count', count: 10_000 },
    reward: { gems: 50, tapMultiplier: 1.2 },
    unlocked: false,
    progress: 0,
    target: 10_000,
  },
  {
    id: 'prestige_first',
    name: 'Reborn',
    description: 'Prestige for the first time',
    emoji: '✨',
    condition: { type: 'prestige_count', count: 1 },
    reward: { gems: 200, incomeMultiplier: 1.3 },
    unlocked: false,
    progress: 0,
    target: 1,
  },
  {
    id: 'property_owner',
    name: 'Property Mogul',
    description: 'Own all 5 properties',
    emoji: '🌆',
    condition: { type: 'property_owned', count: 5 },
    reward: { gems: 120, incomeMultiplier: 1.18 },
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'first_trillion',
    name: 'Trillionaire',
    description: 'Reach $1,000,000,000,000 net worth',
    emoji: '👑',
    condition: { type: 'net_worth', amount: 1_000_000_000_000 },
    reward: { gems: 500, incomeMultiplier: 1.5, tapMultiplier: 1.5 },
    unlocked: false,
    progress: 0,
    target: 1_000_000_000_000,
  },
  {
    id: 'tap_million',
    name: 'Tap Legend',
    description: 'Tap 1,000,000 times',
    emoji: '🔥',
    condition: { type: 'tap_count', count: 1_000_000 },
    reward: { gems: 300, tapMultiplier: 2.0 },
    unlocked: false,
    progress: 0,
    target: 1_000_000,
  },
];
