import { Business } from '../types/game';

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'lemonade_stand',
    name: 'Lemonade Stand',
    emoji: '🍋',
    baseCost: 50,
    baseIncome: 0.5,
    level: 0,
    owned: false,
    multiplier: 1,
    unlockAt: 0,
    description: 'Start small. Every empire begins somewhere.',
  },
  {
    id: 'grocery_store',
    name: 'Grocery Store',
    emoji: '🛒',
    baseCost: 500,
    baseIncome: 5,
    level: 0,
    owned: false,
    multiplier: 1,
    unlockAt: 250,
    description: 'Daily essentials. Steady cash flow.',
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    emoji: '🍔',
    baseCost: 5_000,
    baseIncome: 50,
    level: 0,
    owned: false,
    multiplier: 1,
    unlockAt: 2_000,
    description: 'Fine dining for fine profits.',
  },
  {
    id: 'startup',
    name: 'Tech Startup',
    emoji: '💻',
    baseCost: 50_000,
    baseIncome: 500,
    level: 0,
    owned: false,
    multiplier: 1,
    unlockAt: 20_000,
    description: 'Disrupting the market. Unicorn potential.',
  },
  {
    id: 'factory',
    name: 'Factory',
    emoji: '🏭',
    baseCost: 500_000,
    baseIncome: 5_000,
    level: 0,
    owned: false,
    multiplier: 1,
    unlockAt: 200_000,
    description: 'Mass production. Massive returns.',
  },
  {
    id: 'ai_company',
    name: 'AI Company',
    emoji: '🤖',
    baseCost: 5_000_000,
    baseIncome: 50_000,
    level: 0,
    owned: false,
    multiplier: 1,
    unlockAt: 2_000_000,
    description: 'The future is AI. You own it.',
  },
  {
    id: 'bank',
    name: 'Mega Bank',
    emoji: '🏦',
    baseCost: 50_000_000,
    baseIncome: 500_000,
    level: 0,
    owned: false,
    multiplier: 1,
    unlockAt: 20_000_000,
    description: 'Money makes money. Own the money.',
  },
  {
    id: 'space_company',
    name: 'Space Company',
    emoji: '🚀',
    baseCost: 500_000_000,
    baseIncome: 5_000_000,
    level: 0,
    owned: false,
    multiplier: 1,
    unlockAt: 200_000_000,
    description: 'The stars are the limit.',
  },
];

export const BUSINESS_MILESTONE_MULTIPLIERS: Record<number, number> = {
  10: 2,
  25: 3,
  50: 5,
  100: 10,
  200: 15,
  500: 25,
};
