import { LuxuryItem } from '../types/game';

export const INITIAL_LUXURY_ITEMS: LuxuryItem[] = [
  {
    id: 'sports_car',
    name: 'Supercar',
    emoji: '🏎️',
    cost: 500_000,
    owned: false,
    prestigeBonus: 1,
    incomeMultiplier: 1.05,
    tapMultiplier: 1.1,
    description: 'Zero to rich in 2.9 seconds.',
    category: 'car',
  },
  {
    id: 'gold_watch',
    name: 'Gold Watch',
    emoji: '⌚',
    cost: 200_000,
    owned: false,
    prestigeBonus: 1,
    incomeMultiplier: 1.03,
    tapMultiplier: 1.05,
    description: 'Time is money. Wear both.',
    category: 'watch',
  },
  {
    id: 'mega_yacht',
    name: 'Mega Yacht',
    emoji: '🛥️',
    cost: 5_000_000,
    owned: false,
    prestigeBonus: 3,
    incomeMultiplier: 1.10,
    tapMultiplier: 1.15,
    description: '200ft of pure luxury.',
    category: 'yacht',
  },
  {
    id: 'private_jet',
    name: 'Private Jet',
    emoji: '✈️',
    cost: 20_000_000,
    owned: false,
    prestigeBonus: 5,
    incomeMultiplier: 1.20,
    tapMultiplier: 1.25,
    description: 'Fly private. Think globally.',
    category: 'jet',
  },
  {
    id: 'mega_mansion',
    name: 'Mega Mansion',
    emoji: '🏰',
    cost: 50_000_000,
    owned: false,
    prestigeBonus: 10,
    incomeMultiplier: 1.30,
    tapMultiplier: 1.40,
    description: '20 bedrooms. 5 pools. Yours.',
    category: 'mansion',
  },
  {
    id: 'diamond_watch',
    name: 'Diamond Watch',
    emoji: '💎',
    cost: 2_000_000,
    owned: false,
    prestigeBonus: 2,
    incomeMultiplier: 1.07,
    tapMultiplier: 1.08,
    description: '300 carats of flex.',
    category: 'watch',
  },
  {
    id: 'hypercar',
    name: 'Hypercar Collection',
    emoji: '🚗',
    cost: 10_000_000,
    owned: false,
    prestigeBonus: 4,
    incomeMultiplier: 1.15,
    tapMultiplier: 1.20,
    description: 'One for every day of the week.',
    category: 'car',
  },
  {
    id: 'space_ticket',
    name: 'Space Tourism',
    emoji: '🌌',
    cost: 500_000_000,
    owned: false,
    prestigeBonus: 25,
    incomeMultiplier: 1.50,
    tapMultiplier: 2.0,
    description: 'When earth gets boring.',
    category: 'jet',
  },
];
