import { Property } from '../types/game';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'apartment',
    name: 'Apartment Complex',
    emoji: '🏢',
    baseCost: 10_000,
    rentPerSec: 10,
    appreciationRate: 0.001,
    level: 1,
    owned: false,
    purchasePrice: 0,
    currentValue: 10_000,
    description: 'Steady rental income from urban tenants.',
  },
  {
    id: 'villa',
    name: 'Luxury Villa',
    emoji: '🏡',
    baseCost: 100_000,
    rentPerSec: 100,
    appreciationRate: 0.002,
    level: 1,
    owned: false,
    purchasePrice: 0,
    currentValue: 100_000,
    description: 'Premium waterfront property with high returns.',
  },
  {
    id: 'hotel',
    name: 'Boutique Hotel',
    emoji: '🏨',
    baseCost: 1_000_000,
    rentPerSec: 1_000,
    appreciationRate: 0.003,
    level: 1,
    owned: false,
    purchasePrice: 0,
    currentValue: 1_000_000,
    description: 'Five-star hospitality. Five-star profits.',
  },
  {
    id: 'mall',
    name: 'Shopping Mall',
    emoji: '🛍️',
    baseCost: 10_000_000,
    rentPerSec: 10_000,
    appreciationRate: 0.004,
    level: 1,
    owned: false,
    purchasePrice: 0,
    currentValue: 10_000_000,
    description: 'Retail paradise. Revenue machine.',
  },
  {
    id: 'skyscraper',
    name: 'Skyscraper',
    emoji: '🗼',
    baseCost: 100_000_000,
    rentPerSec: 100_000,
    appreciationRate: 0.005,
    level: 1,
    owned: false,
    purchasePrice: 0,
    currentValue: 100_000_000,
    description: 'Touch the clouds. Own the skyline.',
  },
];
